### ISSUE TITLE
GRPC feasibility

### ISSUE THREAD

**Issue by despiegk** [threefoldtech/dbreboot#18]
- how does it work in web (javascript)
- schema support?
- generation for javascript? (rpc/schema's)
- generation for python
- generation for other languages?

**Comment by muhamadazmy** [comment]
- I have created a simple grpc service that defines a very basic bcdb API. The api implementation so far is not complete, but we return some dummy data (or notimplemented() errors)
- I have generated clients in 3 languages
  - Go
  - Python
  - Javascript

Both the Go, and Python clients works out of the box and can connect directly to the simple bcdb service without a middleware.

The javascript client generation also went very smoothly, but due to browser limitation, js clients can't directly connect to a grpc server, instead they require a middle proxy to translate the grpc-web protocol to grpc. There are few ready to use proxy, but the most common one is [envoy](https://www.envoyproxy.io/)

> I included the envoy.yaml (config file) in my example code.
Once i started the server, I wrote a simple example (example.js) code that uses the generated client and it worked out of the box with no issues
