### ISSUE TITLE
alternative interface to GRPC for BCDB server

### ISSUE THREAD

**Issue by xmonader** [threefoldtech/dbreboot#48]
We want to use bcdb from another language that doesn't have a decent grpc library (with very limited/no streaming support) https://github.com/jgaskins/grpc

demo of what we are trying to do [https://github.com/Hamdy/bcdb-grpc](https://github.com/Hamdy/bcdb-grpc) preferably we can use redis interface to communicate (get/set) or a  REST interface.

**Comment by zaibon** [comment]
The answer is a big NO. This project is not even a month old, ALl the spec are fresh and have been validated before we started implementing it. And now we already want to change the RPC layer. 
So or we drop grpc completely and use something else or you use a decent language that support grpc. But we are not going to maintain 2 RPC layer here.

**Comment by despiegk** [comment]
## requirements

- < can be fixed in less than 1 day FTE (we don't have more time to spend)
- memory is key for crystaltwin/3bot cannot use a new go or other component in between BCDB server & the crystaltwin/3bot

## remarks

- the crystal has no streaming support for GRPC and this can not be easily fixed
- its ok to have more features in GRPC interface compared to a 2nd interface if that would be the solution
- grpc could be a good choice dropping it completely is maybe a little too drastic because we need a simple interface for certain usecase

**Comment by muhamadazmy** [comment]
The API is ready. The docs on how to use the API is here. Currently we have a limitation on the set request body size of 4MB. but we will probably drop this in the future when we support large files (splitting large content into smaller blocks).

The docs for the api is here

https://github.com/threefoldtech/dbreboot/blob/master/docs/api.md

Also check the python client implementation for refernce.
