### ISSUE TITLE
Metadata persistency

### ISSUE THREAD

**Issue by LeeSmet** [threefoldtech/dbreboot#6]
Since metadata lives locally, we need some way to make it persistent across reboots. Either save it in zdb, dump into a file, or maybe use sled, ...

**Comment by muhamadazmy** [comment]
I was looking into sonic and even started building an async client for rust and came across the following findings:
## What we need
- We need to be able to associate metadata in the form of tags to an object ID, for example for an email subsystem that is going to use BCDB as a backend an email object can have the following tags
  - **subsystem**: email
  - **subject**: the subject of the email goes here
  - **sender**: sender email can go here
  - **more**
- A user should be able to find an object using the defined metadata tags, hence a user can find an email by providing 2 tags only as (subsystem: email, sender: john smith)
- A tag must be also partially searchable (only part of the value, for example subject)

## What sonic can offer
- Sonic offers an unstructured full text search, and by unstructured I mean they don't care about the order of the words in sentence, just index of words (minus common words based on the language). It means if you have text (hello world) it doesn't matter if u search (hello world) or (world hello)
- Sonic provides 2 layers of grouping:
  - collection: for example, products, or messages. this fits our "subsystem" exactly
  - bucket: according to docs, this can be user specific (to group user related docs), otherwise use generic name like "default", or "generic"
  - text, that's where all the rest of the terms for index goes. 

## So what is the problem?
The problem can be explained with the following example. Imagine we have to documents with following tags:
- ID: 1 `{tag1: value1, tag2: value2}`
- ID: 2 `{tag2: value1, tag1: value2}`
Now if u search `{tag1: value2}` u expect that you will only get `ID 2` but in face you will get both documents back. The reason is, sonic doesn't know or care about your text structure, it will only return docs that has the query words. In this case, both documents have the word `tag1` and the word `value2` hence both matches.
### Suggested solutions
#### Solution 1
Hash combination of `key: value` and encode to alpha characters only `a-z` and use that to feed the indexer. This will allow use to do **EXACT** match on tags, but will allow to search multiple tags at once
#### Solution 2
Use a bucket for each tag, so each document tag will be inserted into a separate buckets. for example
- PUSH <collection> ID1 tag1 "value1"
- PUSH <collection> ID1 tag2 "value2"
- ... 
This way we can search any tag with full or partial value, but this introduce another problem which is  that we can't search multiple tags, we can only search one tag (bucket) with one query.
>> We can do client side aggregation of the results, but this is going to be very tricky specially if we have may results from each query (also pagination is gonna be a problem)

## Conclution
I don't believe sonic is meant to be used this way. I prefer we look into other options

**Comment by muhamadazmy** [comment]
I haven't looking into this in details but looks promising https://github.com/tantivy-search/tantivy

**Comment by muhamadazmy** [comment]
Okay, so I have looked more into tantivy details and API, and here is what I have learned:
- tantivy supports a simple schema. Basically pre configure the names (plus some options) of the fields of a document that u want to index, then later on you can search one or multiple fields based on your query.
- The schema is very simple but strict. It means after setting up the schema, there is NO way you can modify it (i didn't figure out even how to re build the index). there were some issues open on the repo regarding this, I dropped my question there.
- The API is actually pretty decent and clean, and can be easily embedded in bcdb, I would still recommend it over sonic, since even with the limitation above, already can do more than what sonic can do.
- It's not over regarding adding fields to schema, from this issue [here](https://github.com/tantivy-search/tantivy/issues/301) it looks that it's possible, but not exposed by the API, let's see what they are going to reply

## Possible workaround 
- We still can leverage on a static schema if we changed the `tags` system to `labels` system. The only difference is that then we can use exact matches. A label can be formatted as `<category>.<sub-category>....<value>`
- For example `severity.critical` or `photography.egypt.cairo` more like hashtags in social media.
- If we can do this then a static schema like `schema { labels, body }` can be used, where we can do full text search in body and labels.

> Note: this is still can't be done with sonic because in sonic it only support one field to be queried. unlike tantivy

**Comment by zaibon** [comment]
To solve the static schema issue. Could we link multiple index schema to a same document? So if a user wants to add new tags we just create a second schema. Then during queries we search all the defined schema?
Probably not super efficient though...

**Comment by muhamadazmy** [comment]
@zaibon this is not different from using multiple buckets solution with `sonic`. The problem again will be that we will have to do aggregation in client side. Don't like this solution.
